# Generated by Django 6.0.2 on 2026-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_serviceprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('hospital', 'Hospital'), ('fire', 'Fire Department'), ('ngo', 'NGO')], default='user', max_length=10),
        ),
    ]
