# Generated by Django 6.0.2 on 2026-03-07 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_helper_fields"),
        ("sos", "0003_alter_sosrequest_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="total_earnings",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="total_requests_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serviceprovider",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("hospital", "Hospital"),
                    ("fire", "Fire Department"),
                    ("ngo", "NGO"),
                    ("police", "Police"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("hospital", "Hospital"),
                    ("fire", "Fire Department"),
                    ("ngo", "NGO"),
                    ("police", "Police"),
                ],
                default="user",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earned", "Earned"),
                            ("withdrawn", "Withdrawn"),
                            ("bonus", "Bonus"),
                            ("penalty", "Penalty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sos_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_transactions",
                        to="sos.sosrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
